model_groups:
  - name: gpt-group
    strategy: weighted
    models:
      - name: gpt-4-1
        type: openai
        base_url: https://api.openai.com
        api_key: your-api-key-1
        weight: 2
        max_tokens: 4096
        temperature: 0.7
      - name: gpt-4-2
        type: openai
        base_url: https://api.openai.com
        api_key: your-api-key-2
        weight: 1
        max_tokens: 4096
        temperature: 0.7
  - name: claude-group
    strategy: round-robin
    models:
      - name: claude-1
        type: claude
        base_url: https://api.anthropic.com
        api_key: your-claude-api-key
        weight: 1
        max_tokens: 4096
        temperature: 0.7 